<?php require_once("../../private/initialize.php"); ?>

<?php
    
    $page_title = "Yabe CMS Administrator's Dashboard";
    $style_sheets = [
        "/css/common.css",
        "/css/admin.css"
    ];
    $scripts = [
        "/js/common.js",
    ];
    
    // Automatic redirect to Administrator Authentication page if user hasn't logged in
    if (isset($_SESSION["admin_logged_in"]) && !$_SESSION["admin_logged_in"]) {
        redirect_to(url_for("/admin/auth"));
    }
    
    include(SHARED_PATH . "/top.php");

?>

<main>
  <ul class=breadcrumb>
    <li><a href="<?=url_for("/mall");?>"><i class="fas fa-long-arrow-alt-left mr-10"></i>Back to Yabe Mall</a></li>
  </ul>

  <h1 class="content-title">Yabe CMS Administrator's Dashboard</h1>
  <div class="content-body flex-container">
    <aside class="content-aside-nav content-child">
      <ul>
        <li><a href="<?=url_for("/admin");?>">Welcome</a></li>
        <li><a class="content-aside-nav-active" href="<?=url_for("/admin/manual.php");?>">Administrator's Manual</a></li>
        <li><a href="<?=url_for("/admin/phpinfo.php");?>">PHPInfo</a></li>
        <li><a href="<?=url_for("/admin/logs.php");?>">Logs</a></li>
        <li><a href="<?=url_for("/admin/database_man.php");?>">Database Manager</a></li>
        <li><a href="<?=url_for("/admin/legal_editor.php");?>">Edit Legal Information</a></li>
        <li><a href="<?=url_for("/admin/about_us.php");?>">Edit About Us</a></li>
        <li><a href="<?=url_for("/admin/password.php");?>">Change password</a></li>
        <li><a href="<?=url_for("/admin/auth?q=logout");?>">Log out<i class="fas fa-sign-out-alt ml-10"></i></a></li>
      </ul>
    </aside>

    <section class="content-child admin-content">
      <article>
        <h2>Yabe CMS Administrator's Manual</h2>
        <p class="text-align-justify">CMS stands for Content Management System. You can use the administrative tools provided here to modify website database, access website settings, add/remove account manually, and more advanced operations...</p>
      </article>
      
      <article>
        <h3>Tabe of Contents</h3>
        <ol>
          <li><a href="#admin-manual-01">Overview</a></li>
          <li><a href="#admin-manual-02">PHPInfo</a></li>
          <li><a href="#admin-manual-03">Logs</a></li>
          <li><a href="#admin-manual-04">Database Manager</a></li>
          <li><a href="#admin-manual-05">Edit Legal Information</a></li>
          <li><a href="#admin-manual-06">Edit About Us</a></li>
          <li><a href="#admin-manual-07">Change Password</a></li>
          <li><a href="#admin-manual-08">Advanced Administration</a></li>
        </ol>
      </article>
      
      <article class="text-align-justify">
        <br>
        <h3 id="admin-manual-01" class="admin-content-section-title">Overview</h3>
        <p>
          The Yabe&copy; Administrator Dashboard consists of 6 tabs (not including the "Welcome" and this
          "Administrator's Manual tab"). In each of these tabs, you can manage an aspect of running this website. As
          their names suggested, their functionality can be summarized as follow:
        </p>
        <ul>
          <li><strong>PHPInfo:</strong> Displays the server's current PHP configurations.</li>
          <li><strong>Logs:</strong> Contains all important activities happened on this website.</li>
          <li><strong>Database Manager:</strong> Lets you access and modify the website's internal database.</li>
          <li><strong>Edit Legal Information:</strong> Lets you edit the website's legal pages: Copyright, Terms of
            Service, and Privacy Policy.</li>
          <li><strong>Edit About Us:</strong> Lets you edit the company's bio and its founders' photos.</li>
          <li><strong>Change Password:</strong> Lets you modify your administrator's credentials.</li>
        </ul>
        
        <br>
        <h3 id="admin-manual-02" class="admin-content-section-title">PHPInfo</h3>
        <p>
          This tab displays the output of <strong>php -i</strong> as if you were running it from the command line. There
          is also a link to a preformatted version generated by PHP via the <strong>phpinfo()</strong> function.
        </p>
        <p>
          To edit these configuration, please locate the <strong>php.ini</strong> file your web server is using, and
          edit that file according to your needs. More about the <strong>php.ini</strong> file and how to configure
          PHP's behavior on <a href="https://www.php.net/manual/en/configuration.file.php">www.php.net</a>.
        </p>

        <br>
        <h3 id="admin-manual-03" class="admin-content-section-title">Logs</h3>
        <p>
          This tab displays the contents of <em>/private/logs.txt</em>. Logged site activities include:
        </p>
        <ul>
          <li>Install script (<em>public/install.php</em>).</li>
          <li>Administrator logins and log-outs.</li>
          <li>Administrator dashboard activities.</li>
          <li>Administrator privilege authentication for dangerous actions.</li>
          <li>User logins and log-outs.</li>
          <li>User registrations.</li>
          <li>File uploading operations.</li>
          <li>Database reading/writing operations.</li>
        </ul>
        <p>
          It also has an option for you to clear the logs. However, this is not recommended as it will compromise the
          website's security trace and potentially making security breaches much harder to investigate. Only do this
          when you have a backup of the previous log entries, or that you are certain that the old entries are not
          needed in the future (e.g. system reset, re-installation...).
        </p>

        <br>
        <h3 id="admin-manual-04" class="admin-content-section-title">Database Manager</h3>
        <p>
          This tab enable access to all .csv database files inside <em>/private/database</em>. It displays them as
          editable tables. You can click the <i class="fas fa-low-vision"></i> icon to toggle each table's
          visibility. Please note that you can only edit one database at a time. When you choose "MODIFY" under a
          database table, only that database will be modified. If you have any other changes on other tables, those
          changes will be discarded.
        </p>
        <p>
          To add a new database or remove an existing one, please refer to <a href="#admin-manual-08">Advanced
          Administration</a>.
        </p>

        <br>
        <h3 id="admin-manual-05" class="admin-content-section-title">Edit Legal Information</h3>
        <p>In this tab, you can edit Yabe's legal information on the following 3 pages:</p>
        <ul>
          <li><a href="<?=url_for("/mall/legal/copyright");?>">Copyright</a></li>
          <li><a href="<?=url_for("/mall/legal/tos");?>">Terms of Service</a></li>
          <li><a href="<?=url_for("/mall/legal/privacy-policy");?>">Privacy Policy</a></li>
        </ul>
        <p>
          The editor interface has 2 tabs: Edit and Preview. You need to have basic knowledge of HTML in order to use
          the Edit tab. You can learn more about HTML on <a href="https://www.w3schools.com/html/default.asp">W3Schools</a>.
          The Preview tab displays what the HTML code in the Edit tab would look like on the target page. You can switch
           back and forth between these two tabs any number of time before committing the edit by pressing the "Modify"
          button. There is also a "Reset" option to discard all changes made in the current session.
        </p>
        <p>Please note that once you pressed the "Modify" button, your edits are not revertible.</p>

        <br>
        <h3 id="admin-manual-06" class="admin-content-section-title">Edit About Us</h3>
        <p>This tab contains 2 parts: The bio editor and the photo editor.</p>
        <p>
          The bio editor lets you edit the content of the bio paragraph in <a href="<?=url_for("/mall/about-us");?>">About Us</a>.
          It works similar to the "Edit" tab in <a href="#admin-manual-05">Edit Legal Information</a>. Once you pressed
          the "Modify" button, your changes are permanent. However, you can choose "Reset" if you want to discard those
          changes and start editing from the latest version saved in the website database.
        </p>
        <p>
          The photo editor lets you update the photos for Yabe's founder. Note that it can only be done one at a time
          for each of them, and any changes you made in the bio editor will be discarded on each photo submission.
          Changes made here are also permanent.
        </p>

        <br>
        <h3 id="admin-manual-07" class="admin-content-section-title">Change Password</h3>
        <p>
          You can change your administrator credentials here. You will need to enter the existing administrator's
          password in order for the CMS to verify your new password.
        </p>

        <br>
        <h3 id="admin-manual-08" class="admin-content-section-title">Advanced Administration</h3>
        <p>
          You can have greater control over the system by accessing the command line. It will enable you to access the
          filesystem and modify anything you want. The file structure of this application is as follow:
        </p>
        <p>Public folder (document root):</p>
        <pre><?=str_replace("?", " ", utf8_decode(shell_exec("tree ../")));?></pre>
        <p>Private folder:</p>
        <pre><?=str_replace("?", " ", utf8_decode(shell_exec("tree ../../private")));?></pre>
        <p>Databases (Manually add, edit, and remove databases .csv files here):</p>
        <pre>/private/database</pre>
        <pre class="ml-30"><?=str_replace("?", " ", utf8_decode(shell_exec("ls ../../private/database")));?></pre>
      </article>
    </section>
  </div>
</main>

<?php include(SHARED_PATH . "/bottom.php"); ?>

